version: '3.3'

services: 
  db: 
    image: mysql:latest
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes: 
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  blog:
    depends_on:
      - db
    image: wordpress:latest 
    container_name: wordpress
    volumes: 
      - ./wp_content:/var/www/html/wp-content
    ports:
      - 8000:80
      - 443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password

  php:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: php
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
